apiVersion: v2
name: kps
description: Wrapper Helm chart for deploying kube-prometheus-stack and custom ServiceMonitors
type: application
version: 1.0.0
appVersion: "v0.86.0"
dependencies:
  - name: kube-prometheus-stack
    version: 78.3.0
    repository: "https://prometheus-community.github.io/helm-charts"
