apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.mongo.configMapName }}
data:
  MONGO_HOST: {{ .Values.mongo.host | quote }}
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.mongo.rootUsername | quote }}
  MONGO_REPLICA_SET: {{ .Values.mongo.replicaSet | quote }}