# Global overrides for all subcharts
global:
  host: its-sharon.com

## can enable to use other than latest tag
# feature-flags-api:
#   image:
#     repository: 869432184848.dkr.ecr.ap-south-1.amazonaws.com/feature-flags-service
#     tag: latest


