# Controller configuration
ingress-nginx:
controller:
  ingressClassResource:
    name: nginx
    enabled: true
    default: false  

  service:
    annotations:
          service.beta.kubernetes.io/aws-load-balancer-type: "nlb"

  ports:
    http: 80
    https: 443



# services configuration
featureFlags:
  namespace: default

grafana:
  namespace: kps

kibana:
  namespace: efk


