env: prod
global:
  host: "its-sharon.com"

feature-flags-api:
  image:
    tag: v1.0.19

kibana:
  config:
    server.publicBaseUrl: "https://kibana.its-sharon.com"

mongodb:
  mongo:
    members: 3
