apiVersion: apps/v1
kind: Deployment
metadata:
  name: feature-flags-api
  labels:
    app: feature-flags-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: feature-flags-api
  template:
    metadata:
      labels:
        app: feature-flags-api
    spec:
      imagePullSecrets:
        - name: ecr-creds 
      containers:
      - name: feature-flags-api
        image: 869432184848.dkr.ecr.ap-south-1.amazonaws.com/feature-flags-service:latest
        ports:
        - containerPort: 5000
        envFrom:
        - secretRef:
            name: mongo-secret
        - configMapRef:
            name: mongo-config