apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: feature-flags-prometheus-rules
  namespace: kps
  labels:
    release: kube-prometheus-stack
spec:
  groups:
    - name: feature-flags-api
      rules:
        - alert: HighErrorRate
          expr: |
            (sum(rate(flask_http_request_total{status=~"5.."}[5m]))
             /
             sum(rate(flask_http_request_total[5m]))) > 0.05
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: "High error rate detected in Feature Flags API"
            description: "More than 5% of requests returned 5xx responses over the last 5 minutes."

        - alert: HighResponseLatency
          expr: |
            histogram_quantile(0.95, sum(rate(flask_http_request_duration_seconds_bucket[5m])) by (le)) > 1
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "High response latency in Feature Flags API"
            description: "p95 response time exceeded 1s for the last 5 minutes."
