apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: feature-flags-api-monitor
  namespace: kps
  labels:
    app: feature-flags-api
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: feature-flags-api
  namespaceSelector:
    any: true
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
