apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-external-secret
  namespace: kps
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secret-store
    kind: ClusterSecretStore

  target:
    name: grafna-credentials
    creationPolicy: Owner

  dataFrom:
    - extract:
        key: feature-flags/dev
