# Only create this if external secrets are ENABLED
{{- $secretName := .Values.grafana.secretName | default "grafana-secret" -}}
{{- if .Values.grafana.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-external-secret
  namespace: kps
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-store
    kind: ClusterSecretStore
  target:
    name: {{ $secretName }}
    creationPolicy: Owner
  data:
    - secretKey: admin-user
      remoteRef:
        key: feature-flags/{{ .Values.env }}
        property: admin-user

    - secretKey: admin-password
      remoteRef:
        key: feature-flags/{{ .Values.env }}
        property: admin-password
{{- end }}