{{- $secretName := "grafana-secret" -}}
{{- if .Values.grafana.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-external-secret
  namespace: kps
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-store
    kind: ClusterSecretStore
  target:
    name: {{ $secretName }}
    creationPolicy: Owner
  data:
    - secretKey: admin-user
      remoteRef:
        key: feature-flags/dev
        property: admin-user

    - secretKey: admin-password
      remoteRef:
        key: feature-flags/dev
        property: admin-password

{{- else }}
# LOCAL: Stable Auto-Generation using 'lookup'
{{- $existingSecret := (lookup "v1" "Secret" "kps" $secretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
type: Opaque
data:
  admin-user: {{ "admin" | b64enc | quote }}
  
  {{- if $existingSecret }}
  # Reuse existing password (it is already base64 encoded in k8s)
  admin-password: {{ index $existingSecret.data "admin-password" | quote }}
  {{- else }}
  # Generate new password
  admin-password: {{ randAlphaNum 20 | b64enc | quote }}
  {{- end }}
{{- end }}