global:
  host: "dev.its-sharon.com"
image:
  tag: dev-a721654
kibana:
  publicBaseUrl: "https://kibana.dev.its-sharon.com"

grafana:
  externalSecrets:
    enabled: false

mongo:
  externalSecrets:
    enabled: false
