env: dev
global:
  host: "dev.its-sharon.com"
feature-flags-api:
  image:
    tag: dev-a721654
kibana:
  config:
    server.publicBaseUrl: "https://kibana.dev.its-sharon.com"

mongodb:
  mongo:
    members: 1