apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: feature-flags-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: feature-flags.its-sharon.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: feature-flags-api-service
                port:
                  number: 5000

