apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: root-appset
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: git@github.com:shaarron/feature-flags-resources.git
        revision: main
        files:
          - path: "argocd/applications/*/*.yaml"
  template:
    metadata:
      name: '{{path.basename}}'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: git@github.com:shaarron/feature-flags-resources.git
        targetRevision: main
        path: '{{path}}'
        helm:
          parameters:
            - name: global.host
              value: its-sharon.com  # Cascaded to all apps
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true