prometheus:
  prometheusSpec:
  # discover all ServiceMonitors within its namespace
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
grafana:
  persistence:
    enabled: true
# for local testing only - disable node exporter    
nodeExporter:
  enabled: true