# Enable external-secrets operator subchart
external-secrets:
  enabled: true
  installCRDs: true
  serviceAccount:
    create: false
    name: external-secrets-sa

# External Secrets ServiceAccount configuration
serviceAccount:
  name: external-secrets-sa
  namespace: external-secrets
  iamRoleArn: arn:aws:iam::869432184848:role/external-secrets-role
  syncWave: "0"

# ClusterSecretStore configuration
clusterSecretStore:
  name: aws-secret-store
  syncWave: "2"
  provider:
    aws:
      service: SecretsManager
      region: ap-south-1
