global:
  host: ""  # Provided by ArgoCD

kube-prometheus-stack:
  namespaceOverride: kps

  prometheus:
    prometheusSpec:
      serviceMonitorSelectorNilUsesHelmValues: false
      serviceMonitorSelector: {}
      podMonitorSelectorNilUsesHelmValues: false
      podMonitorSelector: {}

  grafana:
    namespaceOverride: kps
    persistence:
      enabled: true
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations: {}
      hosts:
        - grafana.{{ .Values.global.host }}
      path: /

  kube-state-metrics:
    namespaceOverride: kps

  prometheus-node-exporter:
    namespaceOverride: kps