global:
  host: ""
tlsSecretName: ""

kube-prometheus-stack:
  namespaceOverride: kps

  prometheus:
    prometheusSpec:
      serviceMonitorSelectorNilUsesHelmValues: false
      serviceMonitorSelector: {}
      podMonitorSelectorNilUsesHelmValues: false
      podMonitorSelector: {}

  grafana:
    externalSecrets:
      enabled: false
    admin:
      existingSecret: grafana-secret
      existingSecretUserKey: admin-user
      existingSecretPasswordKey: admin-password

    namespaceOverride: kps
    persistence:
      enabled: true
    
    sidecar:
      dashboards:
        enabled: true
        label: grafana_dashboard
        labelValue: "1"

  kube-state-metrics:
    namespaceOverride: kps

  prometheus-node-exporter:
     namespaceOverride: kps
    