kube-prometheus-stack:
  namespaceOverride: kps

  prometheus:
    prometheusSpec:
      serviceMonitorSelectorNilUsesHelmValues: false
      serviceMonitorSelector: {}
      podMonitorSelectorNilUsesHelmValues: false
      podMonitorSelector: {}

  grafana:
    namespaceOverride: kps
    persistence:
      enabled: true
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /
      hosts:
        - grafana.its-sharon.com

  kube-state-metrics:
    namespaceOverride: kps

  prometheus-node-exporter:
    namespaceOverride: kps