kube-prometheus-stack:
  namespaceOverride: kps

  prometheus:
    prometheusSpec:
      serviceMonitorSelectorNilUsesHelmValues: false
      serviceMonitorSelector: {}
      podMonitorSelectorNilUsesHelmValues: false
      podMonitorSelector: {}

  grafana:
    namespaceOverride: kps
    persistence:
      enabled: true

  kube-state-metrics:
    namespaceOverride: kps

  prometheus-node-exporter:
    enabled: false
    # namespaceOverride: kps

global:
  host: ""     