global:
  host: ""

kube-prometheus-stack:
  namespaceOverride: kps

  prometheus:
    prometheusSpec:
      serviceMonitorSelectorNilUsesHelmValues: false
      serviceMonitorSelector: {}
      podMonitorSelectorNilUsesHelmValues: false
      podMonitorSelector: {}

  grafana:
    admin:
      existingSecret: grafna-credentials
      existingSecretUserKey: USER
      existingSecretPasswordKey: PASSWORD
    namespaceOverride: kps
    persistence:
      enabled: true

    dashboards:
      feature-flags:
        feature-flags-api-monitor.json: 
          json: |
            {{ .Files.Get "feature-flags-api-monitor.json" | indent 10 }} 
    
    sidecar:
      dashboards:
        enabled: true


  kube-state-metrics:
    namespaceOverride: kps

  prometheus-node-exporter:
     namespaceOverride: kps
    