cert-manager:
  enabled: true
  crds:
    enabled: true
  serviceAccount:
    name: cert-manager
    create: false
  
cert-manager-config:
  domain: ""
  wildcardCert:
    secretName: ""
  email: ""

  route53:
    region: ""
    hostedZoneID: ""
