# Enable cert-manager subchart
cert-manager:
  enabled: true
  crds:
    enabled: true
  serviceAccount:
    name: cert-manager
    create: false
  
  wildcardCert:
    secretName: ""
  email: ""

  route53:
    region: ""
    hostedZoneID: ""
