global:
  host: "its-sharon.com"

hostedZoneID: "Z10244981ZAMIY8KVE0M3"

clusterSecretStore:
  provider:
    aws:
      region: "ap-south-1"

ingress: 
  tlsSecretName: "wildcard-itssharon"

certManagerConfig:
  domain: "its-sharon.com"
  email: "sharonkovich@gmail.com"
  route53:
    region: "ap-south-1"
    hostedZoneID: "Z10244981ZAMIY8KVE0M3"
  wildcardCert:
    secretName: "wildcard-itssharon"

mongodb:
  externalSecrets:
    enabled: true

grafana:
  externalSecrets:
    enabled: true
      
# kube-prometheus-stack:
# for local testing - disable node exporter
  # nodeExporter:
  #   enabled: false
  # exporter:
  #   enabled: false

