global:
  host: "its-sharon.com"

tlsSecretName: "its-sharon-com-tls"

# kube-prometheus-stack:
# for local testing - disable node exporter
  # nodeExporter:
  #   enabled: false
  # exporter:
  #   enabled: false

# global:
#   hostedZoneId: ""
#   domainName: "its-sharon.com"
#   environment: ""
#   clusterName: ""
# kibana 
# publicBaseUrl: "https://kibana.{{ .Values.global.host }}"
