apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: feature-flags-ingress
  namespace: {{ .Values.featureFlags.namespace | default "default" }}
spec:
  ingressClassName: nginx
  rules:
    - host: feature-flags.{{ .Values.global.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: feature-flags-api-service
                port:
                  number: 5000
