apiVersion: v1
kind: Service
metadata:
  name: feature-flags-api-service
  labels:
    app: feature-flags-api
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    app: feature-flags-api
