replicaCount: 2

image:
  repository: ghcr.io/shaarron/feature-flags-app/feature-flags-api
  tag: v1.0.13
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5000

mongo:
  secretName: mongo-secret  
  configMapName: mongo-config   
  rootUsername: root1
  host: mongo-svc.default.svc.cluster.local
  database: featureflags
  replicaSet: false

readinessProbe:
  path: /flags
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 2
  failureThreshold: 3
  successThreshold: 1

livenessProbe:
  path: /flags
  initialDelaySeconds: 15
  periodSeconds: 20
  timeoutSeconds: 2
  failureThreshold: 3

resources:
  requests:
    memory: "128Mi"
    cpu: "50m"
  limits:
    memory: "256Mi"
    cpu: "100m"

global:
  host: ""